apiVersion: v1
kind: PersistentVolume

metadata:
  name: pv-volume1

spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 100Mi
  hostPath:
    path: /tmp/k8s-volume1